version: "2"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: npm start
    container_name: node-container
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: bluein
    volumes:
      - ./db/data:/var/lib/mysql
    restart: always